# Generated by Django 3.2.8 on 2021-11-15 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('default_address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('default_city_or_town', models.CharField(blank=True, max_length=50, null=True)),
                ('default_county_or_state', models.CharField(blank=True, max_length=50, null=True)),
                ('default_postcode_or_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
