# Generated by Django 3.2.8 on 2021-11-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub',
        ),
    ]
